site_name: Terra em Bytes - Wiki

theme:
  name: material
  logo: assets/logo_bg_transparente.png
  # configurando o modo claro (Default)
  palette:
    - scheme: default
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-sunny
        name: Mudar para modo escuro

    # configurando o modo escuro (Slate)
    - scheme: slate
      primary: indigo
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Mudar para modo claro
